kind: pipeline
name: build-and-test-amd64

platform:
  os: linux
  arch: amd64

steps:
- name: Build and Test
  image: ubuntu:19.10
  commands:
    - apt-get update -y
    - apt-get install -y make gcc g++ cmake exiv2 libexiv2-dev  qt5-default qtbase5-dev qtbase5-dev-tools qtcreator
    - cmake .
    - make
    - ./shiftpicdate-gui
