name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-ubuntu:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: upgrade
      run: sudo apt update; sudo apt install -y tzdata gcc g++ clang cmake
    - name: install qt
      run: sudo apt install -y qt5-default qtbase5-dev qtbase5-dev-tools qtcreator
    - name: install exiv2
      run: sudo apt install -y exiv2 libexiv2-dev
    - name: configure
      run: mkdir build && cd build && cmake ..
    - name: build
      run: cmake --build build
    - name: run
      run: ./build/./shiftpicdate-gui

